name: Release

on: [push, pull_request]

jobs:
  build:

    runs-on: [ubuntu-latest]


    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup toolchain
      run: |
        rustup target add x86_64-unknown-linux-musl
        rustup update
        cargo --version
        rustup show
        rustup toolchain list
        rustup target list

    - uses: Swatinem/rust-cache@v2


    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: progrs
        path: target/x86_64-unknown-linux-musl/release/progrs
